//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package com.chriszou.pomometronome;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.view.KeyEvent;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.Button;
import android.widget.SeekBar;
import android.widget.TextView;
import com.chriszou.pomometronome.R.id;
import com.chriszou.pomometronome.custom.CountDownView;
import com.googlecode.androidannotations.api.SdkVersionHelper;
import de.passsy.holocircularprogressbar.HoloCircularProgressBar;

public final class PomoActivity_
    extends PomoActivity
{


    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
    }

    private void init_(Bundle savedInstanceState) {
        mPrefs = new MyPrefs_(this);
    }

    private void afterSetContentView_() {
        mRateSeekBar = ((SeekBar) findViewById(id.main_rate_seekbar));
        mCountDownView = ((CountDownView) findViewById(id.main_time_left));
        mPomoSeekBar = ((HoloCircularProgressBar) findViewById(id.main_pomo_seekbar));
        mRateView = ((TextView) findViewById(id.main_rate));
        mStartButton = ((Button) findViewById(id.main_start));
        {
            View view = findViewById(id.main_increase);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        PomoActivity_.this.increaseRate();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.main_decrease);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        PomoActivity_.this.decreaseRate();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.main_start);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        PomoActivity_.this.start();
                    }

                }
                );
            }
        }
        initViews();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        afterSetContentView_();
    }

    @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (((SdkVersionHelper.getSdkInt()< 5)&&(keyCode == KeyEvent.KEYCODE_BACK))&&(event.getRepeatCount() == 0)) {
            onBackPressed();
        }
        return super.onKeyDown(keyCode, event);
    }

    public static PomoActivity_.IntentBuilder_ intent(Context context) {
        return new PomoActivity_.IntentBuilder_(context);
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, PomoActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public PomoActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (context_ instanceof Activity) {
                ((Activity) context_).startActivityForResult(intent_, requestCode);
            } else {
                context_.startActivity(intent_);
            }
        }

    }

}
